### ISSUE TITLE
Invite semiar speakers to slack

### ISSUE THREAD

**Issue by ReneRanzinger** [glycoinfo/GLIC#18]
After all speakers have confirmed to present in the seminar (#13) we should add them to Slack to use the seminar series sub-channel (#17) for coordination.

**Comment by kiyoko** [comment]
@Bribak I just tried to create a private channel for us board members in the GLIC Slack, but I can't seem to find you.  What's your username?

**Comment by ReneRanzinger** [comment]
@kiyoko I can already see the tumbleweed balls rolling through that channel due to activity level.

**Comment by Bribak** [comment]
@kiyoko Now I'm there with my normal name ; though I'd still recommend e-mail for anything time-sensitive. I strive to avoid too many notifications scattered over too many outlets
